/**
 * Issue body generator for the `review` command.
 *
 * Generates GitHub Issue content (title, body, labels) for a backward
 * analysis suggestion. All functions are pure — no I/O side effects.
 *
 * Issue targets the SOURCE repo (e.g. `lecture-python-intro`) since
 * suggestions are about improving the English source material.
 */

import { SuggestionWithContext } from './commands/review.js';
import { CATEGORY_STYLES, confidenceTier } from './review-formatter.js';

// ============================================================================
// LABEL HELPERS
// ============================================================================

/** Map BackportCategory enum value → kebab-case GitHub label */
const CATEGORY_LABEL: Record<string, string> = {
  BUG_FIX:          'bug-fix',
  CLARIFICATION:    'clarification',
  EXAMPLE:          'example',
  CODE_IMPROVEMENT: 'code-improvement',
  I18N_ONLY:        'i18n-only',
  NO_CHANGE:        'no-change',
};

/** Map confidence tier → GitHub label */
const TIER_LABEL: Record<string, string> = {
  high:   'confidence-high',
  medium: 'confidence-medium',
  low:    'confidence-low',
};

/**
 * Returns labels to attach to the created GitHub Issue.
 *
 * Always includes:
 * - `backward-suggestion`
 * - category-specific label (e.g. `bug-fix`)
 * - confidence-tier label  (e.g. `confidence-high`)
 */
export function getIssueLabels(item: SuggestionWithContext): string[] {
  const { category, confidence } = item.suggestion;
  return [
    'backward-suggestion',
    CATEGORY_LABEL[category] ?? category.toLowerCase().replace(/_/g, '-'),
    TIER_LABEL[confidenceTier(confidence)] ?? 'confidence-low',
  ];
}

// ============================================================================
// TITLE
// ============================================================================

/** Maximum characters for the suggestion summary in the title */
const MAX_TITLE_SUMMARY_CHARS = 80;

/**
 * Format a concise Issue title:
 *   [filename] Brief one-line summary
 *
 * Truncates the summary at `MAX_TITLE_SUMMARY_CHARS` and appends "…" if needed.
 */
export function formatIssueTitle(item: SuggestionWithContext): string {
  const summary = item.suggestion.summary.length > MAX_TITLE_SUMMARY_CHARS
    ? item.suggestion.summary.slice(0, MAX_TITLE_SUMMARY_CHARS).trimEnd() + '…'
    : item.suggestion.summary;

  return `[${item.file}] ${summary}`;
}

// ============================================================================
// BODY
// ============================================================================

/**
 * Format a full GitHub Issue body in Markdown for a backward suggestion.
 *
 * Includes:
 * - Category, confidence, file location
 * - Section heading
 * - Full LLM reasoning
 * - Specific changes (numbered, Before/After)
 * - "Generated by `resync backward`" footer
 */
export function formatIssueBody(item: SuggestionWithContext): string {
  const { file, timestamp, sourceRepo, targetRepo, suggestion } = item;
  const { sectionHeading, category, confidence, summary, reasoning, specificChanges } = suggestion;

  const categoryStyle = CATEGORY_STYLES[category] ?? { label: category };
  const tier = confidenceTier(confidence);
  const pct = (confidence * 100).toFixed(0) + '%';
  const date = timestamp ? timestamp.slice(0, 10) : new Date().toISOString().slice(0, 10);

  const lines: string[] = [];

  // ── Summary block ─────────────────────────────────────────────────────────
  lines.push('## Summary');
  lines.push('');
  lines.push(`> ${summary}`);
  lines.push('');

  // ── Metadata table ────────────────────────────────────────────────────────
  lines.push('## Details');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| **File** | \`${file}\` |`);
  lines.push(`| **Section** | \`${sectionHeading}\` |`);
  lines.push(`| **Category** | ${categoryStyle.label} |`);
  lines.push(`| **Confidence** | ${pct} (${tier}) |`);
  if (sourceRepo) lines.push(`| **Source repo** | ${sourceRepo} |`);
  if (targetRepo) lines.push(`| **Target repo** | ${targetRepo} |`);
  lines.push('');

  // ── Reasoning ─────────────────────────────────────────────────────────────
  lines.push('## Analysis');
  lines.push('');
  lines.push(reasoning.trim());
  lines.push('');

  // ── Specific changes ──────────────────────────────────────────────────────
  if (specificChanges.length > 0) {
    lines.push(`## Suggested Change${specificChanges.length > 1 ? 's' : ''}`);
    lines.push('');

    for (let i = 0; i < specificChanges.length; i++) {
      const change = specificChanges[i];
      if (specificChanges.length > 1) {
        lines.push(`### ${i + 1}. ${change.type}`);
      } else {
        lines.push(`**${change.type}**`);
      }
      lines.push('');

      if (change.original) {
        lines.push('**Before:**');
        lines.push('');
        lines.push('```');
        lines.push(change.original.trim());
        lines.push('```');
        lines.push('');
      }

      if (change.improved) {
        lines.push('**After:**');
        lines.push('');
        lines.push('```');
        lines.push(change.improved.trim());
        lines.push('```');
        lines.push('');
      }
    }
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by \`resync backward\` on ${date}.*`);
  lines.push('');

  return lines.join('\n');
}


