/**
 * Issue body generator for the `review` command.
 *
 * Generates GitHub Issue content (title, body, labels) for a backward
 * analysis suggestion. All functions are pure — no I/O side effects.
 *
 * Issue targets the SOURCE repo (e.g. `lecture-python-intro`) since
 * suggestions are about improving the English source material.
 */

import { SuggestionWithContext } from './commands/review.js';
import { CATEGORY_STYLES, confidenceTier } from './review-formatter.js';

// ============================================================================
// LABEL HELPERS
// ============================================================================

/**
 * Map BackportCategory enum value → namespaced GitHub label.
 *
 * Categories are consolidated:
 * - BUG_FIX         → translate:bug-fix
 * - CLARIFICATION   → translate:narrative  (prose/pedagogical)
 * - EXAMPLE         → translate:narrative  (prose/pedagogical)
 * - CODE_IMPROVEMENT → translate:code
 *
 * I18N_ONLY and NO_CHANGE never reach the review stage
 * (filtered out by filterActionableSuggestions), so they are omitted.
 */
const CATEGORY_LABEL: Record<string, string> = {
  BUG_FIX:          'translate:bug-fix',
  CLARIFICATION:    'translate:narrative',
  EXAMPLE:          'translate:narrative',
  CODE_IMPROVEMENT: 'translate:code',
};

/**
 * Extract the language code from a targetRepo name.
 *
 * Convention: `{repo-name}.{language}` → e.g. "lecture-intro.zh-cn" → "zh-cn"
 * Falls back to the full targetRepo string if no dot is found.
 */
export function extractLanguage(targetRepo: string): string {
  const dotIdx = targetRepo.indexOf('.');
  return dotIdx >= 0 ? targetRepo.slice(dotIdx + 1) : targetRepo;
}

/**
 * Returns labels to attach to the created GitHub Issue.
 *
 * Every issue gets exactly 3 labels:
 * - `translate`                  — common tag for all translation-sourced issues
 * - `translate:{category}`       — e.g. `translate:bug-fix`
 * - `translate:{language}`       — e.g. `translate:zh-cn`
 *
 * If targetRepo is absent the language label is omitted (2 labels).
 */
export function getIssueLabels(item: SuggestionWithContext): string[] {
  const { category } = item.suggestion;
  const labels = [
    'translate',
    CATEGORY_LABEL[category] ?? `translate:${category.toLowerCase().replace(/_/g, '-')}`,
  ];

  if (item.targetRepo) {
    labels.push(`translate:${extractLanguage(item.targetRepo)}`);
  }

  return labels;
}

// ============================================================================
// TITLE
// ============================================================================

/**
 * Push a fenced code block onto `lines`, using enough backticks to avoid
 * collision with any backtick runs inside `content`.
 *
 * If `content` contains ``` the outer fence uses ``````, etc.
 */
function pushFencedBlock(lines: string[], content: string): void {
  // Find the longest run of consecutive backticks in content
  let maxRun = 0;
  const matches = content.match(/`+/g);
  if (matches) {
    for (const m of matches) {
      if (m.length > maxRun) maxRun = m.length;
    }
  }
  // Outer fence must be at least maxRun + 1 backticks, minimum 3
  const fence = '`'.repeat(Math.max(3, maxRun + 1));
  lines.push(fence);
  lines.push(content);
  lines.push(fence);
}

/** Maximum characters for the suggestion summary in the title */
const MAX_TITLE_SUMMARY_CHARS = 80;

/**
 * Format a concise Issue title:
 *   [filename] Brief one-line summary
 *
 * Truncates the summary at `MAX_TITLE_SUMMARY_CHARS` and appends "…" if needed.
 */
export function formatIssueTitle(item: SuggestionWithContext): string {
  const summary = item.suggestion.summary.length > MAX_TITLE_SUMMARY_CHARS
    ? item.suggestion.summary.slice(0, MAX_TITLE_SUMMARY_CHARS).trimEnd() + '…'
    : item.suggestion.summary;

  return `[${item.file}] ${summary}`;
}

// ============================================================================
// BODY
// ============================================================================

/**
 * Format a full GitHub Issue body in Markdown for a backward suggestion.
 *
 * Includes:
 * - Category, confidence, file location
 * - Section heading
 * - Full LLM reasoning
 * - Specific changes (numbered, Before/After)
 * - "Generated by `resync backward`" footer
 */
export function formatIssueBody(item: SuggestionWithContext): string {
  const { file, timestamp, sourceRepo, targetRepo, suggestion } = item;
  const { sectionHeading, category, confidence, summary, reasoning, specificChanges } = suggestion;

  const categoryStyle = CATEGORY_STYLES[category] ?? { label: category };
  const tier = confidenceTier(confidence);
  const pct = (confidence * 100).toFixed(0) + '%';
  const date = timestamp ? timestamp.slice(0, 10) : new Date().toISOString().slice(0, 10);

  const lines: string[] = [];

  // ── Summary block ─────────────────────────────────────────────────────────
  lines.push('## Summary');
  lines.push('');
  lines.push(summary);
  lines.push('');

  // ── Metadata table ────────────────────────────────────────────────────────
  lines.push('## Details');
  lines.push('');
  lines.push('| Field | Value |');
  lines.push('|-------|-------|');
  lines.push(`| **File** | \`${file}\` |`);
  lines.push(`| **Section** | \`${sectionHeading}\` |`);
  lines.push(`| **Category** | ${categoryStyle.label} |`);
  lines.push(`| **Confidence** | ${pct} (${tier}) |`);
  if (sourceRepo) lines.push(`| **Source repo** | ${sourceRepo} |`);
  if (targetRepo) lines.push(`| **Target repo** | ${targetRepo} |`);
  lines.push('');

  // ── Reasoning ─────────────────────────────────────────────────────────────
  lines.push('## Analysis');
  lines.push('');
  lines.push(reasoning.trim());
  lines.push('');

  // ── Specific changes ──────────────────────────────────────────────────────
  if (specificChanges.length > 0) {
    lines.push(`## Suggested Change${specificChanges.length > 1 ? 's' : ''}`);
    lines.push('');

    for (let i = 0; i < specificChanges.length; i++) {
      const change = specificChanges[i];
      if (specificChanges.length > 1) {
        lines.push(`### ${i + 1}. ${change.type}`);
      } else {
        lines.push(`**${change.type}**`);
      }
      lines.push('');

      if (change.original) {
        lines.push('**Before:**');
        lines.push('');
        pushFencedBlock(lines, change.original.trim());
        lines.push('');
      }

      if (change.improved) {
        lines.push('**After:**');
        lines.push('');
        pushFencedBlock(lines, change.improved.trim());
        lines.push('');
      }
    }
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by \`resync backward\` on ${date}.*`);
  lines.push('');

  return lines.join('\n');
}


