/**
 * Report Generator
 * 
 * Formats backward analysis results as Markdown or JSON reports.
 * 
 * Report tone: Suggestions, not corrections. SOURCE is the source of truth.
 * Uses language like "The translation may have identified..." rather than "Fix this."
 */

import { BackwardReport, BulkBackwardReport, BackportSuggestion } from './types';
import { formatDate, formatTimelineForPrompt } from './git-metadata';

// ============================================================================
// MARKDOWN REPORTS
// ============================================================================

/**
 * Generate a Markdown report for a single file backward analysis
 */
export function generateMarkdownReport(report: BackwardReport): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Backward Analysis: ${report.file}`);
  lines.push('');
  lines.push(`**Generated**: ${report.timestamp}`);
  if (report.model) {
    lines.push(`**Model**: ${report.model}`);
  }
  if (report.sourceRepo || report.targetRepo) {
    lines.push(`**SOURCE**: ${report.sourceRepo || 'unknown'} | **TARGET**: ${report.targetRepo || 'unknown'}`);
  }

  // Git metadata
  if (report.sourceMetadata) {
    lines.push(`**SOURCE last modified**: ${formatDate(report.sourceMetadata.lastModified)} by ${report.sourceMetadata.lastAuthor}`);
  }
  if (report.targetMetadata) {
    lines.push(`**TARGET last modified**: ${formatDate(report.targetMetadata.lastModified)} by ${report.targetMetadata.lastAuthor}`);
  }
  lines.push('');

  // Overall verdict (clear top-level summary)
  const backportCount = report.suggestions.filter(s => s.recommendation === 'BACKPORT').length;
  if (report.triageResult.verdict === 'IN_SYNC') {
    lines.push('**Result: ✅ IN SYNC** — No backport suggestions.');
  } else if (backportCount > 0) {
    lines.push(`**Result: 📋 ${backportCount} SUGGESTION${backportCount === 1 ? '' : 'S'}** — See details below.`);
  } else if (report.triageResult.verdict === 'CHANGES_DETECTED') {
    lines.push('**Result: ✅ NO ACTION NEEDED** — Differences found but none require backporting.');
  } else {
    lines.push('**Result: ⚠️ SKIPPED** — Document too large for triage.');
  }
  lines.push('');

  // Triage result
  lines.push('## Stage 1: Document Triage');
  lines.push('');
  lines.push(`**Verdict**: ${report.triageResult.verdict}`);
  if (report.triageResult.notes) {
    lines.push(`**Notes**: ${report.triageResult.notes}`);
  }
  lines.push('');

  // Quick exit if no suggestions
  if (report.triageResult.verdict === 'IN_SYNC') {
    lines.push('The translation appears to be a faithful rendering of the source. No backport suggestions.');
    lines.push('');
    appendTimeline(lines, report);
    return lines.join('\n');
  }

  if (report.triageResult.verdict === 'SKIPPED_TOO_LARGE') {
    lines.push('Document was too large for single-call triage. Section-level analysis was performed directly.');
    lines.push('');
  }

  // Suggestions
  const backportSuggestions = report.suggestions.filter(s => s.recommendation === 'BACKPORT');
  const noBackportSuggestions = report.suggestions.filter(s => s.recommendation === 'NO_BACKPORT');

  if (backportSuggestions.length === 0) {
    lines.push('## Stage 2: Section Analysis');
    lines.push('');
    lines.push('No backport suggestions found after detailed section analysis.');
    lines.push('');

    // Still show per-section reasoning even when no backports
    if (noBackportSuggestions.length > 0) {
      lines.push('## Sections Reviewed');
      lines.push('');
      for (const s of noBackportSuggestions) {
        lines.push(`- **${s.sectionHeading}**: ${s.category} — ${s.summary}`);
      }
      lines.push('');
    }

    appendTimeline(lines, report);
    return lines.join('\n');
  }

  lines.push(`## Suggestions (${backportSuggestions.length} found)`);
  lines.push('');

  for (const suggestion of backportSuggestions) {
    lines.push(formatSuggestion(suggestion));
    lines.push('');
  }

  // Summary of reviewed sections with no suggestions
  if (noBackportSuggestions.length > 0) {
    lines.push('## Sections Reviewed (No Suggestions)');
    lines.push('');
    for (const s of noBackportSuggestions) {
      lines.push(`- **${s.sectionHeading}**: ${s.category} — ${s.summary}`);
    }
    lines.push('');
  }

  appendTimeline(lines, report);

  lines.push('*This report was generated by `resync backward`. Suggestions are for consideration by source maintainers.*');
  lines.push('');

  return lines.join('\n');
}

/**
 * Append the commit timeline as an appendix section
 */
function appendTimeline(lines: string[], report: BackwardReport): void {
  if (report.timeline) {
    lines.push('---');
    lines.push('');
    lines.push('## Appendix: Commit Timeline');
    lines.push('');
    lines.push('```');
    lines.push(formatTimelineForPrompt(report.timeline));
    lines.push('```');
    lines.push('');
  }
}

/**
 * Format a single suggestion in Markdown
 */
function formatSuggestion(suggestion: BackportSuggestion): string {
  const lines: string[] = [];

  const confidenceLabel = suggestion.confidence >= 0.85 ? 'HIGH' 
    : suggestion.confidence >= 0.6 ? 'MEDIUM' : 'LOW';

  lines.push(`### ${suggestion.sectionHeading} (${confidenceLabel} confidence: ${suggestion.confidence.toFixed(2)})`);
  lines.push(`**Category**: ${suggestion.category}`);
  lines.push('');
  lines.push(suggestion.summary);
  lines.push('');

  if (suggestion.specificChanges.length > 0) {
    for (const change of suggestion.specificChanges) {
      lines.push(`**${change.type}**:`);
      if (change.original) {
        lines.push('');
        lines.push('*Current English*:');
        lines.push(`> ${change.original}`);
        lines.push('');
      }
      if (change.improved) {
        lines.push('*Suggested improvement*:');
        lines.push(`> ${change.improved}`);
        lines.push('');
      }
    }
  }

  if (suggestion.reasoning) {
    lines.push(`**Reasoning**: ${suggestion.reasoning}`);
  }

  return lines.join('\n');
}

// ============================================================================
// BULK MARKDOWN REPORTS
// ============================================================================

/**
 * Generate a summary Markdown report for bulk backward analysis
 */
export function generateBulkMarkdownReport(report: BulkBackwardReport): string {
  const lines: string[] = [];

  lines.push('# Backward Analysis Report');
  lines.push('');
  lines.push(`**Generated**: ${report.timestamp}`);
  if (report.model) {
    lines.push(`**Model**: ${report.model}`);
  }
  lines.push(`**Source**: ${report.sourceRepo}`);
  lines.push(`**Target**: ${report.targetRepo} (${report.language})`);
  lines.push('');

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Files analyzed | ${report.filesAnalyzed} |`);
  lines.push(`| Files in sync | ${report.filesInSync} |`);
  lines.push(`| Files with suggestions | ${report.filesFlagged} |`);
  lines.push(`| Files skipped (too large) | ${report.filesSkipped} |`);
  lines.push(`| Total suggestions | ${report.totalSuggestions} |`);
  lines.push(`| High confidence (≥0.85) | ${report.highConfidence} |`);
  lines.push(`| Medium confidence (0.6-0.85) | ${report.mediumConfidence} |`);
  lines.push(`| Low confidence (<0.6) | ${report.lowConfidence} |`);
  lines.push('');

  // Per-file details (only files with suggestions)
  const filesWithSuggestions = report.fileReports.filter(
    f => f.suggestions.some(s => s.recommendation === 'BACKPORT')
  );

  if (filesWithSuggestions.length > 0) {
    lines.push('## Files with Suggestions');
    lines.push('');

    for (const fileReport of filesWithSuggestions) {
      const suggestions = fileReport.suggestions.filter(s => s.recommendation === 'BACKPORT');
      lines.push(`### ${fileReport.file} (${suggestions.length} suggestion${suggestions.length === 1 ? '' : 's'})`);
      lines.push('');

      for (const suggestion of suggestions) {
        lines.push(formatSuggestion(suggestion));
        lines.push('');
      }
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('*This report was generated by `resync backward`. Suggestions are for consideration by source maintainers.*');
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// JSON REPORTS
// ============================================================================

/**
 * Generate a JSON report for a single file backward analysis
 */
export function generateJsonReport(report: BackwardReport): string {
  return JSON.stringify(report, null, 2);
}

/**
 * Generate a JSON report for bulk backward analysis
 */
export function generateBulkJsonReport(report: BulkBackwardReport): string {
  return JSON.stringify(report, null, 2);
}
