/**
 * Setup Command — Scaffold a new target translation repository
 *
 * Creates a GitHub repo, copies scaffolding files, plants .translate/config.yml,
 * creates the translation sync workflow, and makes an initial commit.
 *
 * Usage:
 *   translate setup --source QuantEcon/lecture-python-intro --target-language zh-cn
 *   translate setup --source QuantEcon/lecture-python-intro --target-language zh-cn --dry-run
 *
 * Pairs with `translate init` for the complete onboarding workflow:
 *   setup → init → push → configure Action
 */

import * as fs from 'fs';
import * as path from 'path';
import { spawnSync } from 'child_process';
import { writeConfig } from '../translate-state.js';
import { TranslateConfig } from '../types.js';

// ============================================================================
// TYPES
// ============================================================================

export interface SetupOptions {
  source: string;             // GitHub owner/repo (e.g., "QuantEcon/lecture-python-intro")
  targetLanguage: string;     // Target language code (e.g., "zh-cn")
  sourceLanguage: string;     // Source language code (default: "en")
  docsFolder: string;         // Documentation folder within repos (default: "lectures")
  visibility: 'public' | 'private';  // Repo visibility (default: "public")
  dryRun: boolean;            // Preview without creating
}

export interface SetupResult {
  repoName: string;           // e.g., "lecture-python-intro.zh-cn"
  repoFullName: string;       // e.g., "QuantEcon/lecture-python-intro.zh-cn"
  localPath: string;          // Local clone path
  filesCreated: string[];     // Files written to the repo
  success: boolean;
  error?: string;
}

/**
 * Injectable runner for `gh` CLI calls (testability).
 */
export type GhRunner = (
  args: string[],
) => { stdout: string; stderr: string; status: number | null };

/**
 * Injectable runner for `git` CLI calls (testability).
 */
export type GitRunner = (
  args: string[],
  opts?: { cwd?: string },
) => { stdout: string; stderr: string; status: number | null };

// ============================================================================
// RUNNERS (I/O)
// ============================================================================

export function realGhRunner(args: string[]): ReturnType<GhRunner> {
  const result = spawnSync('gh', args, { encoding: 'utf8', timeout: 30_000 }) as {
    stdout: string; stderr: string; status: number | null; error?: Error;
  };
  if (result.error) {
    const err = result.error as NodeJS.ErrnoException;
    if (err.code === 'ENOENT') throw new Error('`gh` CLI not found. Install from https://cli.github.com/');
    throw result.error;
  }
  return { stdout: result.stdout ?? '', stderr: result.stderr ?? '', status: result.status };
}

export function realGitRunner(args: string[], opts?: { cwd?: string }): ReturnType<GitRunner> {
  const result = spawnSync('git', args, { encoding: 'utf8', cwd: opts?.cwd, timeout: 30_000 }) as {
    stdout: string; stderr: string; status: number | null; error?: Error;
  };
  if (result.error) throw result.error;
  return { stdout: result.stdout ?? '', stderr: result.stderr ?? '', status: result.status };
}

// ============================================================================
// REPO NAME DERIVATION
// ============================================================================

/**
 * Derive target repo name from source repo + language.
 * "lecture-python-intro" + "zh-cn" → "lecture-python-intro.zh-cn"
 */
export function deriveTargetRepoName(sourceRepo: string, language: string): string {
  // sourceRepo is "owner/repo" — extract the repo part
  const repoName = sourceRepo.includes('/') ? sourceRepo.split('/')[1] : sourceRepo;
  return `${repoName}.${language}`;
}

/**
 * Extract owner from "owner/repo" format.
 */
function extractOwner(sourceRepo: string): string {
  if (!sourceRepo.includes('/')) {
    throw new Error(`Source must be in owner/repo format (got "${sourceRepo}")`);
  }
  return sourceRepo.split('/')[0];
}

// ============================================================================
// WORKFLOW TEMPLATE
// ============================================================================

/**
 * Generate the translation sync workflow YAML content.
 */
export function generateWorkflowYaml(
  sourceRepo: string,
  targetLanguage: string,
  docsFolder: string,
  actionVersion: string,
): string {
  return `# Auto-generated by \`translate setup\`
name: Translation Sync

on:
  repository_dispatch:
    types: [translation-sync]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync translations
        uses: QuantEcon/action-translation@v${actionVersion}
        with:
          mode: sync
          source-repo: ${sourceRepo}
          target-language: ${targetLanguage}
          docs-folder: ${docsFolder}
          anthropic-api-key: \${{ secrets.ANTHROPIC_API_KEY }}
          github-token: \${{ secrets.GITHUB_TOKEN }}
`;
}

// ============================================================================
// SCAFFOLDING FILES
// ============================================================================

/**
 * Generate .gitignore content for a translation repo.
 */
function generateGitignore(): string {
  return `# Build outputs
_build/
__pycache__/

# OS files
.DS_Store
Thumbs.db

# Environment
.env
`;
}

// ============================================================================
// MAIN COMMAND
// ============================================================================

/**
 * Run the setup command — scaffold a new target translation repository.
 */
export async function runSetup(
  options: SetupOptions,
  ghRunner: GhRunner = realGhRunner,
  gitRunner: GitRunner = realGitRunner,
): Promise<SetupResult> {
  const owner = extractOwner(options.source);
  const targetRepoName = deriveTargetRepoName(options.source, options.targetLanguage);
  const targetFullName = `${owner}/${targetRepoName}`;
  const localPath = path.resolve(targetRepoName);
  const filesCreated: string[] = [];

  if (options.dryRun) {
    console.log(`\n🔍 DRY RUN — would create:\n`);
    console.log(`  Repository: ${targetFullName} (${options.visibility})`);
    console.log(`  Local clone: ${localPath}`);
    console.log(`  Files:`);
    console.log(`    .translate/config.yml`);
    console.log(`    .github/workflows/translation-sync.yml`);
    console.log(`    .gitignore`);
    console.log(`    README.md`);
    console.log('');
    return {
      repoName: targetRepoName,
      repoFullName: targetFullName,
      localPath,
      filesCreated: ['.translate/config.yml', '.github/workflows/translation-sync.yml', '.gitignore', 'README.md'],
      success: true,
    };
  }

  // Step 1: Create GitHub repo and clone
  console.log(`\n📦 Creating repository ${targetFullName}…`);
  const createResult = ghRunner([
    'repo', 'create', targetFullName,
    `--${options.visibility}`,
    '--clone',
    '--description', `${options.targetLanguage} translation of ${options.source}`,
  ]);

  if (createResult.status !== 0) {
    return {
      repoName: targetRepoName,
      repoFullName: targetFullName,
      localPath,
      filesCreated,
      success: false,
      error: `gh repo create failed: ${createResult.stderr.trim()}`,
    };
  }

  // Step 2: Write scaffolding files
  console.log(`📁 Writing scaffolding files…`);

  // .translate/config.yml
  const config: TranslateConfig = {
    'source-language': options.sourceLanguage,
    'target-language': options.targetLanguage,
    'docs-folder': options.docsFolder,
  };
  writeConfig(localPath, config);
  filesCreated.push('.translate/config.yml');

  // .github/workflows/translation-sync.yml
  const workflowDir = path.join(localPath, '.github', 'workflows');
  fs.mkdirSync(workflowDir, { recursive: true });
  const workflowContent = generateWorkflowYaml(
    options.source,
    options.targetLanguage,
    options.docsFolder,
    '0.8.0',
  );
  fs.writeFileSync(path.join(workflowDir, 'translation-sync.yml'), workflowContent, 'utf-8');
  filesCreated.push('.github/workflows/translation-sync.yml');

  // .gitignore
  fs.writeFileSync(path.join(localPath, '.gitignore'), generateGitignore(), 'utf-8');
  filesCreated.push('.gitignore');

  // README.md
  const readmeContent = `# ${targetRepoName}\n\n${options.targetLanguage} translation of [${options.source}](https://github.com/${options.source}).\n\nGenerated by [\`translate setup\`](https://github.com/QuantEcon/action-translation).\n`;
  fs.writeFileSync(path.join(localPath, 'README.md'), readmeContent, 'utf-8');
  filesCreated.push('README.md');

  // Step 3: Initial commit
  console.log(`📝 Making initial commit…`);
  gitRunner(['add', '.'], { cwd: localPath });
  gitRunner(['commit', '-m', `Initial scaffold for ${options.targetLanguage} translation`], { cwd: localPath });

  // Step 4: Push
  console.log(`🚀 Pushing to origin…`);
  const pushResult = gitRunner(['push', '-u', 'origin', 'main'], { cwd: localPath });
  if (pushResult.status !== 0) {
    // Try HEAD (in case default branch isn't main)
    const fallbackResult = gitRunner(['push', '-u', 'origin', 'HEAD'], { cwd: localPath });
    if (fallbackResult.status !== 0) {
      console.error(`❌ Push failed. You may need to push manually from ${localPath}`);
      return {
        repoName: targetRepoName,
        repoFullName: targetFullName,
        localPath,
        filesCreated,
        success: false,
      };
    }
  }

  console.log(`\n✅ Repository created: ${targetFullName}`);
  console.log(`   Local path: ${localPath}`);
  console.log(`\nNext steps:`);
  console.log(`  1. Add ANTHROPIC_API_KEY secret: gh secret set ANTHROPIC_API_KEY -R ${targetFullName}`);
  console.log(`  2. Translate content: translate init -s /path/to/${options.source.split('/')[1]} -t ${localPath} --target-language ${options.targetLanguage}`);
  console.log('');

  return {
    repoName: targetRepoName,
    repoFullName: targetFullName,
    localPath,
    filesCreated,
    success: true,
  };
}
